version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-codigo-certo
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root123